version: "3.8"

services:
  api:
    build:
      dockerfile: ./dockerfiles/Dockerfile.server.main
    ports:
      - 5002:5002
    environment:
      PEER: True
      HAS_PORT: True
    depends_on:
      - "helper"
  
  web:
    build:
      dockerfile: ./dockerfiles/Dockerfile.client
    ports:
      - 30002:3002
    depends_on:
      - "api"
    command: ["./wait-for-it.sh", "api:5002", "--timeout=10", "--strict", "--", "npm", "run", "start" ]