APP_PORT = 5000
PEER_HELPER_PORT = 5001
TRUSTED_CLIENT_PORT = 3000
PEER_PORT = None

BASE_URL = 'http://localhost'
APP_ADDRESS = BASE_URL
PEER_HELPER_ADDRESS = BASE_URL
PEER_ADDRESS = BASE_URL
TEST_ADDRESS = f'{APP_ADDRESS}:{APP_PORT}'
TRUSTED_CLIENT_ADDRESS = f'{BASE_URL}:{TRUSTED_CLIENT_PORT}'

SUBSCRIBE_KEY = None
PUBLISH_KEY = None

NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = { 'address': '*--official-mining-reward--*' }