FROM node:16.17.1-alpine
WORKDIR usr/app
COPY ./frontend/package.json ./package.json
COPY ./frontend/package-lock.json ./package-lock.json
COPY ./frontend/public ./public
COPY ./frontend/src ./src
RUN npm ci
EXPOSE 3000
CMD [ "npm", "run", "start" ]
