FROM python:3.10.6

WORKDIR usr/src

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend ./backend

EXPOSE 5001

CMD [ "python", "-m", "backend.peer_helper" ]